apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorerdb
  name: explorerdb
  namespace: org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorerdb
  strategy: {}
  template:
    metadata:
      labels:
        app: explorerdb
    spec:
      containers:
      - image: hyperledger/explorer-db:latest
        name: explorer-db
        resources: {}
        envFrom:
        - secretRef:
            name: explorerdb
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: explorerdb
  name: explorerdb
  namespace: org1
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: explorerdb
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: explorerdb
  namespace: org1
data:
  DATABASE_DATABASE: ZmFicmljZXhwbG9yZXI=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_USERNAME: aHBwb2M=
---
